# Data Science Pandas - Joins, Time Series & Rolling Statistics

## Tasks Today:

1) <b>Pandas</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Joins <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - merge() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Breaking Down the Inner Join <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Outer Joins <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Use Case Example <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Rolling Statistics and Time Series w/Pandas <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - read_csv() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - shift() <br>

In [1]:
import pandas as pd
import numpy as np

C:\Users\todds\anaconda3\lib\site-packages\numpy\core\getlimits.py:172: RuntimeWarning: divide by zero encountered in exp2
  eps=exp2(ld(-112)),
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\getlimits.py:51: RuntimeWarning: divide by zero encountered in log10
  self.precision = int(-log10(self.eps))
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\getlimits.py:52: RuntimeWarning: divide by zero encountered in power
  self.resolution = float_to_float(float_conv(10) ** (-self.precision))
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\getlimits.py:184: RuntimeWarning: divide by zero encountered in exp2
  epsneg_f80 = exp2(ld(-64))
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\getlimits.py:185: RuntimeWarning: divide by zero encountered in exp2
  tiny_f80 = exp2(ld(-16382))
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\getlimits.py:199: RuntimeWarning: divide by zero encountered in exp2
  eps=exp2(ld(-63)),
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\getlimits.py:211: RuntimeWarning: divide by zero encountered in nextafter
  huge_dd = (umath.nextafter(ld(inf), ld(0))
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\getlimits.py:224: RuntimeWarning: divide by zero encountered in exp2
  eps=exp2(ld(-105)),
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\getlimits.py:225: RuntimeWarning: divide by zero encountered in exp2
  epsneg= exp2(ld(-106)),
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\getlimits.py:227: RuntimeWarning: divide by zero encountered in exp2
  tiny=exp2(ld(-1022)))
C:\Users\todds\anaconda3\lib\site-packages\numpy\__init__.py:343: RuntimeWarning: divide by zero encountered in subtract
  if not abs(x.dot(x) - 2.0) < 1e-5:
C:\Users\todds\anaconda3\lib\site-packages\numpy\__init__.py:343: RuntimeWarning: divide by zero encountered in absolute
  if not abs(x.dot(x) - 2.0) < 1e-5:
<frozen importlib._bootstrap>:219: RuntimeWarning: divide by zero encountered in add

### Joins <br>
<p>Very often you will have to combine data from several different sources to obtain the actual dataset you need for your exploration or modeling. Pandas draws heavily on SQL in its API design for joins, and if you are familiar with SQL joins, then Pandas will come naturally. Imagine you have two tables, one with customer name and gender, and the other with their purchases:</p>

In [2]:
# Generate some fake data
city_data = {
    1: 'Chicago',
    2: 'Boston',
    3: 'New York',
    4: 'San Francisco',
    5: 'Washington D.C.'
}

ages = np.random.randint(18,65, 100)
city = [ city_data[num] for num in np.random.randint(1,6,100)]
customer_id = np.arange(1000,1100)

C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

<p>Let's assume we have a dataset containing the customer ID's cities, and ages for a set of customers. Suppose further, that we have a second table, containing some customer ID's, and a feedback survey rating from those customers. Suppose finally, that you as an analyst are asked the following question: What city tends to give the best feedback for our product? We'll need a join operation to get the answer.</p>

In [3]:
customer_demographics = pd.DataFrame.from_dict({
    'ages': ages,
    'city': city,
    'customer_id': customer_id
})

customer_demographics

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\concat.py:339: RuntimeWarning: divide by zero encountered in equal
  if (indexer == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\array_algos\take.py:534: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:62: RuntimeWarning: divide by zero encountered in reduce
  return umr_all(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\concat.py:339: RuntimeWarning: divide by zero encountered in equal
  if (indexer == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\array_algos\take.py:534: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:62: RuntimeWarning: divide by zero encountered in reduce
  return umr_all(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred

    ages             city  customer_id
0     20    San Francisco         1000
1     64          Chicago         1001
2     36    San Francisco         1002
3     63           Boston         1003
4     38           Boston         1004
..   ...              ...          ...
95    44  Washington D.C.         1095
96    24  Washington D.C.         1096
97    57         New York         1097
98    49         New York         1098
99    62  Washington D.C.         1099

[100 rows x 3 columns]

In [4]:
# Generate some other fake data
customer_id = np.random.randint(1000,1200, 100)
customer_rating = np.random.randint(1,11,100)

surveys = pd.DataFrame.from_dict({
    'customer_id': customer_id,
    'customer_rating': customer_rating
})

surveys.head(20)

C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)

    customer_id  customer_rating
0          1087                6
1          1007                2
2          1090               10
3          1084                7
4          1086                6
5          1115               10
6          1085                9
7          1125                8
8          1077                3
9          1142                1
10         1080                8
11         1173                7
12         1161                1
13         1159                4
14         1109                3
15         1182                3
16         1133                5
17         1158                5
18         1035                7
19         1182                8

##### merge()

<p>We can zip the two dataframes up with an inner join, using the Pandas API as follows:</p>

In [5]:
demo_ratings = customer_demographics.merge(surveys, on = 'customer_id', how = 'inner')

demo_ratings

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexes\base.py:6015: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:795: RuntimeWarning: divide by zero encountered in int_scalars
  max_len = max(len(mgr_locs), taker.max() + 1)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2178: RuntimeWarning: divide by zero encountered in equal
  lmask = llab == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2180: RuntimeWarning: divide by zero encountered in equal
  rmask = rlab == -1
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2221: RuntimeWarning: divide by zero encountered in multiply
  lkey = stride * llab[0].astype("i8", subok=False, copy=False)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2222: RuntimeWarning: divide by zero encountered in multiply
  rkey = stride * rlab[0].astype("i8", subok=False, copy=False)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\numeric.py:2453: RuntimeWarning: divide by zero encountered in equal
  return bool(asarray(a1 == a2).all())
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:62: RuntimeWarning: divide by zero encountered in reduce
  return umr_all(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\concat.py:339: RuntimeWarning: divide by zero encountered in equal
  if (indexer == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\array_algos\take.py:534: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:854: RuntimeWarning: divide by zero encountered in equal
  left_has_missing = (left_indexer == -1).any()
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred

    ages             city  customer_id  customer_rating
0     20    San Francisco         1000                8
1     64          Chicago         1001                3
2     63           Boston         1003                2
3     36          Chicago         1006               10
4     29         New York         1007                2
5     33           Boston         1010                9
6     44  Washington D.C.         1015                8
7     34          Chicago         1022                2
8     59          Chicago         1025                6
9     21         New York         1029               10
10    21    San Francisco         1032                1
11    54         New York         1035                7
12    54         New York         1035                2
13    54         New York         1036                9
14    61           Boston         1038                7
15    19    San Francisco         1042                7
16    25         New York         1045                8
17    23    San Francisco         1050                9
18    22    San Francisco         1051                4
19    64         New York         1052                7
20    24    San Francisco         1054                5
21    24    San Francisco         1054                5
22    45          Chicago         1056                1
23    52  Washington D.C.         1058               10
24    56         New York         1060                8
25    48         New York         1068                2
26    34           Boston         1070                8
27    34           Boston         1070                3
28    34         New York         1077                3
29    34         New York         1077                4
30    25         New York         1080                8
31    25         New York         1080                3
32    58    San Francisco         1084                7
33    46          Chicago         1085                9
34    46          Chicago         1085                2
35    38         New York         1086                6
36    53  Washington D.C.         1087                6
37    46  Washington D.C.         1088                5
38    31         New York         1090               10
39    57         New York         1097                4
40    57         New York         1097                3

In [6]:
demo_ratings = customer_demographics.merge(surveys, on = 'customer_id', how = 'inner')

demo_ratings

demo_ratings_dropped = demo_ratings.drop_duplicates(subset = 'customer_id').reset_index(drop=True)

demo_ratings_dropped

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexes\base.py:6015: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:795: RuntimeWarning: divide by zero encountered in int_scalars
  max_len = max(len(mgr_locs), taker.max() + 1)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2178: RuntimeWarning: divide by zero encountered in equal
  lmask = llab == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2180: RuntimeWarning: divide by zero encountered in equal
  rmask = rlab == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2221: RuntimeWarning: divide by zero encountered in multiply
  lkey = stride * llab[0].astype("i8", subok=False, copy=False)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2222: RuntimeWarning: divide by zero encountered in multiply
  rkey = stride * rlab[0].astype("i8", subok=False, copy=False)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\numeric.py:2453: RuntimeWarning: divide by zero encountered in equal
  return bool(asarray(a1 == a2).all())
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:62: RuntimeWarning: divide by zero encountered in reduce
  return umr_all(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\concat.py:339: RuntimeWarning: divide by zero encountered in equal
  if (indexer == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\array_algos\take.py:534: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:854: RuntimeWarning: divide by zero encountered in equal
  left_has_missing = (left_indexer == -1).any()
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexes\base.py:3208: RuntimeWarning: divide by zero encountered in not_equal
  indexer = indexer.take((indexer != -1).nonzero()[0])
C:\Users\todds\anaconda3\lib\site-packages\numpy\lib\arraysetops.py:579: RuntimeWarning: divide by zero encountered in not_equal
  mask &= (ar1 != a)
C:\Users\todds\anaconda3\lib\site-packages\numpy\lib\arraysetops.py:579: RuntimeWarning: divide by zero encountered in bitwise_and
  mask &= (ar1 != a)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\algorithms.py:769: RuntimeWarning: divide by zero encountered in equal
  code_is_na = codes == na_sentinel
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:141: RuntimeWarning: divide by zero encountered in equal
  return (lab + 1, size + 1) if (lab == -1).any() else (lab, size)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:161: RuntimeWarning: divide by zero encountered in multiply
  out = stride * labels[0].astype("i8", subok=False, copy=False)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\generic.py:1494: RuntimeWarning: divide by zero encountered in invert
  arr = operator.inv(values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:284: RuntimeWarning: divide by zero encountered in less
  mask = indices < 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in greater_equal
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in less
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in bitwise_or
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred

    ages             city  customer_id  customer_rating
0     20    San Francisco         1000                8
1     64          Chicago         1001                3
2     63           Boston         1003                2
3     36          Chicago         1006               10
4     29         New York         1007                2
5     33           Boston         1010                9
6     44  Washington D.C.         1015                8
7     34          Chicago         1022                2
8     59          Chicago         1025                6
9     21         New York         1029               10
10    21    San Francisco         1032                1
11    54         New York         1035                7
12    54         New York         1036                9
13    61           Boston         1038                7
14    19    San Francisco         1042                7
15    25         New York         1045                8
16    23    San Francisco         1050                9
17    22    San Francisco         1051                4
18    64         New York         1052                7
19    24    San Francisco         1054                5
20    45          Chicago         1056                1
21    52  Washington D.C.         1058               10
22    56         New York         1060                8
23    48         New York         1068                2
24    34           Boston         1070                8
25    34         New York         1077                3
26    25         New York         1080                8
27    58    San Francisco         1084                7
28    46          Chicago         1085                9
29    38         New York         1086                6
30    53  Washington D.C.         1087                6
31    46  Washington D.C.         1088                5
32    31         New York         1090               10
33    57         New York         1097                4

**.join() method**

In [7]:
demo_surveys_join = customer_demographics.join(other = surveys.set_index('customer_id'), on = 'customer_id', how = 'inner')

demo_surveys_join

demo_surveys_join_nodups = demo_surveys_join.drop_duplicates(subset = 'customer_id').reset_index(drop = True)

demo_surveys_join_nodups

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\numeric.py:2453: RuntimeWarning: divide by zero encountered in equal
  return bool(asarray(a1 == a2).all())
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:62: RuntimeWarning: divide by zero encountered in reduce
  return umr_all(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:1196: RuntimeWarning: divide by zero encountered in invert
  taker = (~is_deleted).nonzero()[0]
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:284: RuntimeWarning: divide by zero encountered in less
  mask = indices < 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in greater_equal
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in less
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in bitwise_or
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:737: RuntimeWarning: divide by zero encountered in int_scalars
  slice(ml, ml + 1), new_mgr_locs=BlockPlacement(i)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:1199: RuntimeWarning: divide by zero encountered in invert
  new_columns = self.items[~is_deleted]
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2178: RuntimeWarning: divide by zero encountered in equal
  lmask = llab == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2180: RuntimeWarning: divide by zero encountered in equal
  rmask = rlab == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2221: RuntimeWarning: divide by zero encountered in multiply
  lkey = stride * llab[0].astype("i8", subok=False, copy=False)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2222: RuntimeWarning: divide by zero encountered in multiply
  rkey = stride * rlab[0].astype("i8", subok=False, copy=False)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\concat.py:339: RuntimeWarning: divide by zero encountered in equal
  if (indexer == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\array_algos\take.py:534: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:854: RuntimeWarning: divide by zero encountered in equal
  left_has_missing = (left_indexer == -1).any()
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexes\base.py:3208: RuntimeWarning: divide by zero encountered in not_equal
  indexer = indexer.take((indexer != -1).nonzero()[0])
C:\Users\todds\anaconda3\lib\site-packages\numpy\lib\arraysetops.py:579: RuntimeWarning: divide by zero encountered in not_equal
  mask &= (ar1 != a)
C:\Users\todds\anaconda3\lib\site-packages\numpy\lib\arraysetops.py:579: RuntimeWarning: divide by zero encountered in bitwise_and
  mask &= (ar1 != a)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\algorithms.py:769: RuntimeWarning: divide by zero encountered in equal
  code_is_na = codes == na_sentinel
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:141: RuntimeWarning: divide by zero encountered in equal
  return (lab + 1, size + 1) if (lab == -1).any() else (lab, size)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:161: RuntimeWarning: divide by zero encountered in multiply
  out = stride * labels[0].astype("i8", subok=False, copy=False)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\generic.py:1494: RuntimeWarning: divide by zero encountered in invert
  arr = operator.inv(values)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred

    ages             city  customer_id  customer_rating
0     20    San Francisco         1000                8
1     64          Chicago         1001                3
2     63           Boston         1003                2
3     36          Chicago         1006               10
4     29         New York         1007                2
5     33           Boston         1010                9
6     44  Washington D.C.         1015                8
7     34          Chicago         1022                2
8     59          Chicago         1025                6
9     21         New York         1029               10
10    21    San Francisco         1032                1
11    54         New York         1035                7
12    54         New York         1036                9
13    61           Boston         1038                7
14    19    San Francisco         1042                7
15    25         New York         1045                8
16    23    San Francisco         1050                9
17    22    San Francisco         1051                4
18    64         New York         1052                7
19    24    San Francisco         1054                5
20    45          Chicago         1056                1
21    52  Washington D.C.         1058               10
22    56         New York         1060                8
23    48         New York         1068                2
24    34           Boston         1070                8
25    34         New York         1077                3
26    25         New York         1080                8
27    58    San Francisco         1084                7
28    46          Chicago         1085                9
29    38         New York         1086                6
30    53  Washington D.C.         1087                6
31    46  Washington D.C.         1088                5
32    31         New York         1090               10
33    57         New York         1097                4

<p>Now it's a simple groupby operation to reveal the answer:</p>

In [8]:
city_ages_ratings = demo_ratings_dropped.groupby('city', as_index = False).mean().round(decimals = 2)[['city','ages','customer_rating']]

city_ages_ratings

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexes\base.py:6015: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:795: RuntimeWarning: divide by zero encountered in int_scalars
  max_len = max(len(mgr_locs), taker.max() + 1)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\series.py:2392: RuntimeWarning: divide by zero encountered in multiply
  result = self._values.round(decimals)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\series.py:2392: RuntimeWarning: divide by zero encountered in rint
  result = self._values.round(decimals)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\series.py:2392: RuntimeWarning: divide by zero encountered in true_divide
  result = self._values.round(decimals)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexing.py:1357: RuntimeWarning: divide by zero encountered in less
  missing_mask = indexer < 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:47: RuntimeWarning: divide by zero encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:284: RuntimeWarning: divide by zero encountered in less
  mask = indices < 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in greater_equal
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in less
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in bitwise_or
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:254: RuntimeWarning: divide by zero encountered in isnan
  result = np.isnan(values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1498: RuntimeWarning: divide by zero encountered in absolute
  abs_vals = np.abs(self.values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1502: RuntimeWarning: divide by zero encountered in greater
  has_large_values = (abs_vals > 1e6).any()
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in less
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in greater
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in bitwise_and
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:254: RuntimeWarning: divide by zero encountered in isnan
  result = np.isnan(values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1498: RuntimeWarning: divide by zero encountered in absolute
  abs_vals = np.abs(self.values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1502: RuntimeWarning: divide by zero encountered in greater
  has_large_values = (abs_vals > 1e6).any()
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in less
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in greater
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in bitwise_and
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)

              city   ages  customer_rating
0           Boston  47.75             6.50
1          Chicago  47.33             5.17
2         New York  41.23             6.46
3    San Francisco  26.71             5.86
4  Washington D.C.  48.75             7.25

But what if we didn't drop the customer_id duplicates...would we get the same city result??

In [9]:
city_ages_ratings_dups = demo_ratings.groupby('city', as_index = False).mean().round(decimals = 2)[['city','ages','customer_rating']]

city_ages_ratings_dups

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexes\base.py:6015: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:795: RuntimeWarning: divide by zero encountered in int_scalars
  max_len = max(len(mgr_locs), taker.max() + 1)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\series.py:2392: RuntimeWarning: divide by zero encountered in multiply
  result = self._values.round(decimals)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\series.py:2392: RuntimeWarning: divide by zero encountered in rint
  result = self._values.round(decimals)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\series.py:2392: RuntimeWarning: divide by zero encountered in true_divide
  result = self._values.round(decimals)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexing.py:1357: RuntimeWarning: divide by zero encountered in less
  missing_mask = indexer < 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:47: RuntimeWarning: divide by zero encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:284: RuntimeWarning: divide by zero encountered in less
  mask = indices < 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in greater_equal
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in less
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in bitwise_or
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:254: RuntimeWarning: divide by zero encountered in isnan
  result = np.isnan(values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1498: RuntimeWarning: divide by zero encountered in absolute
  abs_vals = np.abs(self.values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1502: RuntimeWarning: divide by zero encountered in greater
  has_large_values = (abs_vals > 1e6).any()
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in less
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in greater
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in bitwise_and
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:254: RuntimeWarning: divide by zero encountered in isnan
  result = np.isnan(values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1498: RuntimeWarning: divide by zero encountered in absolute
  abs_vals = np.abs(self.values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1502: RuntimeWarning: divide by zero encountered in greater
  has_large_values = (abs_vals > 1e6).any()
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in less
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in greater
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in bitwise_and
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)

              city   ages  customer_rating
0           Boston  45.00             5.80
1          Chicago  47.14             4.71
2         New York  41.53             5.65
3    San Francisco  26.38             5.75
4  Washington D.C.  48.75             7.25

What would be the total mean for the US customers?

In [10]:
city_ratings_mean = demo_ratings_dropped.groupby('city').mean()

city_ratings_mean.loc['Boston']

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexes\base.py:6015: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:795: RuntimeWarning: divide by zero encountered in int_scalars
  max_len = max(len(mgr_locs), taker.max() + 1)

ages                 47.75
customer_id        1030.25
customer_rating       6.50
Name: Boston, dtype: float64

##### Breaking Down the Inner Join <br>
<p>Let's take a closer look at the actual mechanics here however. There is some subtlety and nuance that is best understood by thinking of an inner join as two steps: a cartesian product, and then a filter. Observe the result of the following inner join:</p>

In [11]:
d = {
    'A':[1,2,3,4,2],
    'B': ['a','b','c','d','x']
}

df1 = pd.DataFrame.from_dict(d)
df1

C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred

   A  B
0  1  a
1  2  b
2  3  c
3  4  d
4  2  x

In [12]:
d2 = {
    'A': [1,2,6,2,2],
    'C': ['e','f','g','h','y']
}

df2 = pd.DataFrame.from_dict(d2)
df2

C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred

   A  C
0  1  e
1  2  f
2  6  g
3  2  h
4  2  y

In [13]:
df1.merge(df2, on = 'A', how = 'inner')

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexes\base.py:6015: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:795: RuntimeWarning: divide by zero encountered in int_scalars
  max_len = max(len(mgr_locs), taker.max() + 1)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2178: RuntimeWarning: divide by zero encountered in equal
  lmask = llab == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2180: RuntimeWarning: divide by zero encountered in equal
  rmask = rlab == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2221: RuntimeWarning: divide by zero encountered in multiply
  lkey = stride * llab[0].astype("i8", subok=False, copy=False)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2222: RuntimeWarning: divide by zero encountered in multiply
  rkey = stride * rlab[0].astype("i8", subok=False, copy=False)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\numeric.py:2453: RuntimeWarning: divide by zero encountered in equal
  return bool(asarray(a1 == a2).all())
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:62: RuntimeWarning: divide by zero encountered in reduce
  return umr_all(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\concat.py:339: RuntimeWarning: divide by zero encountered in equal
  if (indexer == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\array_algos\take.py:534: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:854: RuntimeWarning: divide by zero encountered in equal
  left_has_missing = (left_indexer == -1).any()
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred

   A  B  C
0  1  a  e
1  2  b  f
2  2  b  h
3  2  b  y
4  2  x  f
5  2  x  h
6  2  x  y

<p>Somehow, we ended up with more rows in the result than either of the original tables! This is because we joined on a $\textit{non-unique index}$. The join starts by computing all the possible combinations of rows, and then filters them based on the condition. Because of the duplicates, multiple combinations of rows make it through!</p>

### Outer Joins <br>
<p>An $\textit{outer join}$ produces all of the rows from the left table, and joins whatever rows it can to the right table, filling anywhere it cant with NaN's or None values. Below is a brief example, and then we will discuss a possible use case for this type of join.</p>

In [14]:
df3 = pd.DataFrame.from_dict({
    'A':[1,2,3],
    'B': ['a','b','c']
})

df4 = pd.DataFrame.from_dict({
    'A': [1],
    'C': ['d']
})

In [15]:
df3

C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred

   A  B
0  1  a
1  2  b
2  3  c

In [16]:
df4

C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred

   A  C
0  1  d

In [17]:
df3.merge(df4, on = 'A', how = 'outer')

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexes\base.py:6015: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:795: RuntimeWarning: divide by zero encountered in int_scalars
  max_len = max(len(mgr_locs), taker.max() + 1)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2178: RuntimeWarning: divide by zero encountered in equal
  lmask = llab == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2180: RuntimeWarning: divide by zero encountered in equal
  rmask = rlab == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2221: RuntimeWarning: divide by zero encountered in multiply
  lkey = stride * llab[0].astype("i8", subok=False, copy=False)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2222: RuntimeWarning: divide by zero encountered in multiply
  rkey = stride * rlab[0].astype("i8", subok=False, copy=False)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\numeric.py:2453: RuntimeWarning: divide by zero encountered in equal
  return bool(asarray(a1 == a2).all())
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:62: RuntimeWarning: divide by zero encountered in reduce
  return umr_all(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\concat.py:339: RuntimeWarning: divide by zero encountered in equal
  if (indexer == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\array_algos\take.py:534: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:854: RuntimeWarning: divide by zero encountered in equal
  left_has_missing = (left_indexer == -1).any()
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred

   A  B    C
0  1  a    d
1  2  b  NaN
2  3  c  NaN

In [18]:
# LEFT JOIN MERGE
df3.merge(df4, on = 'A', how = 'left')

df1.merge(df2, on = 'A', how = 'left')

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexes\base.py:6015: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:795: RuntimeWarning: divide by zero encountered in int_scalars
  max_len = max(len(mgr_locs), taker.max() + 1)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2178: RuntimeWarning: divide by zero encountered in equal
  lmask = llab == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2180: RuntimeWarning: divide by zero encountered in equal
  rmask = rlab == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2221: RuntimeWarning: divide by zero encountered in multiply
  lkey = stride * llab[0].astype("i8", subok=False, copy=False)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2222: RuntimeWarning: divide by zero encountered in multiply
  rkey = stride * rlab[0].astype("i8", subok=False, copy=False)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\numeric.py:2453: RuntimeWarning: divide by zero encountered in equal
  return bool(asarray(a1 == a2).all())
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:62: RuntimeWarning: divide by zero encountered in reduce
  return umr_all(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\concat.py:339: RuntimeWarning: divide by zero encountered in equal
  if (indexer == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\array_algos\take.py:534: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:854: RuntimeWarning: divide by zero encountered in equal
  left_has_missing = (left_indexer == -1).any()
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred

   A  B    C
0  1  a    e
1  2  b    f
2  2  b    h
3  2  b    y
4  3  c  NaN
5  4  d  NaN
6  2  x    f
7  2  x    h
8  2  x    y

In [19]:
# RIGHT JOIN MERGE
df3.merge(df4, on = 'A', how = 'right')

df1.merge(df2, on = 'A', how = 'right')

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexes\base.py:6015: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:795: RuntimeWarning: divide by zero encountered in int_scalars
  max_len = max(len(mgr_locs), taker.max() + 1)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2178: RuntimeWarning: divide by zero encountered in equal
  lmask = llab == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2180: RuntimeWarning: divide by zero encountered in equal
  rmask = rlab == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2221: RuntimeWarning: divide by zero encountered in multiply
  lkey = stride * llab[0].astype("i8", subok=False, copy=False)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2222: RuntimeWarning: divide by zero encountered in multiply
  rkey = stride * rlab[0].astype("i8", subok=False, copy=False)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\numeric.py:2453: RuntimeWarning: divide by zero encountered in equal
  return bool(asarray(a1 == a2).all())
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:62: RuntimeWarning: divide by zero encountered in reduce
  return umr_all(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\concat.py:339: RuntimeWarning: divide by zero encountered in equal
  if (indexer == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\array_algos\take.py:534: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:854: RuntimeWarning: divide by zero encountered in equal
  left_has_missing = (left_indexer == -1).any()
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:901: RuntimeWarning: divide by zero encountered in equal
  mask_left = left_indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:902: RuntimeWarning: divide by zero encountered in equal
  mask_right = right_indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:913: RuntimeWarning: divide by zero encountered in invert
  key_col = Index(lvals).where(~mask_left, rvals)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexes\base.py:4472: RuntimeWarning: divide by zero encountered in invert
  return self.putmask(~cond, other)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:47: RuntimeWarning: divide by zero encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:1090: RuntimeWarning: divide by zero encountered in invert
  new_blknos[~is_deleted] = np.arange(self.nblocks - len(removed_blknos))
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred

   A    B  C
0  1    a  e
1  2    b  f
2  2    x  f
3  6  NaN  g
4  2    b  h
5  2    x  h
6  2    b  y
7  2    x  y

##### Use Case Example

<p>As an example use case, let's imagine we have again the demographics and survey response tables from above:</p>

In [20]:
customer_demographics.head()

C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred

   ages           city  customer_id
0    20  San Francisco         1000
1    64        Chicago         1001
2    36  San Francisco         1002
3    63         Boston         1003
4    38         Boston         1004

In [21]:
surveys.head()

C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)

   customer_id  customer_rating
0         1087                6
1         1007                2
2         1090               10
3         1084                7
4         1086                6

<p>Now, you are asked as an analyst to compare the demographics of survey responders to the demographics of all your customers combined.</p>

In [22]:
demo_ratings_outer = customer_demographics.merge(surveys, on = 'customer_id', how = 'outer')

demo_ratings_outer['customer_rating'] = demo_ratings_outer['customer_rating'].fillna('N/A')
demo_ratings_outer.head(20)

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexes\base.py:6015: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:795: RuntimeWarning: divide by zero encountered in int_scalars
  max_len = max(len(mgr_locs), taker.max() + 1)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2178: RuntimeWarning: divide by zero encountered in equal
  lmask = llab == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2180: RuntimeWarning: divide by zero encountered in equal
  rmask = rlab == -1
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2221: RuntimeWarning: divide by zero encountered in multiply
  lkey = stride * llab[0].astype("i8", subok=False, copy=False)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:2222: RuntimeWarning: divide by zero encountered in multiply
  rkey = stride * rlab[0].astype("i8", subok=False, copy=False)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\numeric.py:2453: RuntimeWarning: divide by zero encountered in equal
  return bool(asarray(a1 == a2).all())
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:62: RuntimeWarning: divide by zero encountered in reduce
  return umr_all(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\concat.py:339: RuntimeWarning: divide by zero encountered in equal
  if (indexer == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\array_algos\take.py:534: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:854: RuntimeWarning: divide by zero encountered in equal
  left_has_missing = (left_indexer == -1).any()
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:901: RuntimeWarning: divide by zero encountered in equal
  mask_left = left_indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:902: RuntimeWarning: divide by zero encountered in equal
  mask_right = right_indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:913: RuntimeWarning: divide by zero encountered in invert
  key_col = Index(lvals).where(~mask_left, rvals)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexes\base.py:4472: RuntimeWarning: divide by zero encountered in invert
  return self.putmask(~cond, other)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:47: RuntimeWarning: divide by zero encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:1090: RuntimeWarning: divide by zero encountered in invert
  new_blknos[~is_deleted] = np.arange(self.nblocks - len(removed_blknos))
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:254: RuntimeWarning: divide by zero encountered in isnan
  result = np.isnan(values)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:254: RuntimeWarning: divide by zero encountered in isnan
  result = np.isnan(values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1498: RuntimeWarning: divide by zero encountered in absolute
  abs_vals = np.abs(self.values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1502: RuntimeWarning: divide by zero encountered in greater
  has_large_values = (abs_vals > 1e6).any()
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in less
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in greater
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in bitwise_and
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:254: RuntimeWarning: divide by zero encountered in isnan
  result = np.isnan(values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1498: RuntimeWarning: divide by zero encountered in absolute
  abs_vals = np.abs(self.values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1502: RuntimeWarning: divide by zero encountered in greater
  has_large_values = (abs_vals > 1e6).any()
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in less
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in greater
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in bitwise_and
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred

    ages             city  customer_id customer_rating
0   20.0    San Francisco         1000             8.0
1   64.0          Chicago         1001             3.0
2   36.0    San Francisco         1002             N/A
3   63.0           Boston         1003             2.0
4   38.0           Boston         1004             N/A
5   55.0  Washington D.C.         1005             N/A
6   36.0          Chicago         1006            10.0
7   29.0         New York         1007             2.0
8   23.0         New York         1008             N/A
9   39.0    San Francisco         1009             N/A
10  33.0           Boston         1010             9.0
11  52.0    San Francisco         1011             N/A
12  20.0         New York         1012             N/A
13  50.0  Washington D.C.         1013             N/A
14  23.0  Washington D.C.         1014             N/A
15  44.0  Washington D.C.         1015             8.0
16  22.0    San Francisco         1016             N/A
17  49.0          Chicago         1017             N/A
18  44.0           Boston         1018             N/A
19  34.0           Boston         1019             N/A

In [23]:
# Count all survey responders against the total number of customers we have 
# (Specifically the customers that haven't taken the survey yet)
demo_size = demo_ratings_outer.groupby(['city', 'customer_rating']).size()
print(type(demo_size))

# Producing similar result with .count()
demo_count = demo_ratings_outer.groupby(['city', 'customer_rating']).count()
print(type(demo_count))
demo_count

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\algorithms.py:769: RuntimeWarning: divide by zero encountered in equal
  code_is_na = codes == na_sentinel
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\algorithms.py:1844: RuntimeWarning: divide by zero encountered in invert
  nums = np.sort(values[~str_pos])
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:161: RuntimeWarning: divide by zero encountered in multiply
  out = stride * labels[0].astype("i8", subok=False, copy=False)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:167: RuntimeWarning: divide by zero encountered in longlong_scalars
  stride //= lshape[i]
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:168: RuntimeWarning: divide by zero encountered in multiply
  out += labels[i] * stride
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:168: RuntimeWarning: divide by zero encountered in add
  out += labels[i] * stride
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:171: RuntimeWarning: divide by zero encountered in equal
  mask = labels[0] == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:173: RuntimeWarning: divide by zero encountered in equal
  mask |= lab == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:173: RuntimeWarning: divide by zero encountered in bitwise_or
  mask |= lab == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:690: RuntimeWarning: divide by zero encountered in less
  mask = labels < 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\groupby\ops.py:856: RuntimeWarning: divide by zero encountered in not_equal
  out = np.bincount(ids[ids != -1], minlength=ngroups)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:231: RuntimeWarning: divide by zero encountered in subtract
  labels = (x - y) % (factor * shape[i]) // factor
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:231: RuntimeWarning: divide by zero encountered in remainder
  labels = (x - y) % (factor * shape[i]) // factor
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:231: RuntimeWarning: divide by zero encountered in floor_divide
  labels = (x - y) % (factor * shape[i]) // factor
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:232: RuntimeWarning: divide by zero encountered in less
  np.putmask(labels, comp_labels < 0, -1)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:234: RuntimeWarning: divide by zero encountered in multiply
  y = labels * factor
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\numeric.py:2453: RuntimeWarning: divide by zero encountered in equal
  return bool(asarray(a1 == a2).all())
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:62: RuntimeWarning: divide by zero encountered in reduce
  return umr_all(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexes\base.py:6015: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:795: RuntimeWarning: divide by zero encountered in int_scalars
  max_len = max(len(mgr_locs), taker.max() + 1)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\groupby\generic.py:1731: RuntimeWarning: divide by zero encountered in not_equal
  mask = ids != -1

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexes\multi.py:1339: RuntimeWarning: divide by zero encountered in equal
  mask = level_codes == -1
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexes\multi.py:1339: RuntimeWarning: divide by zero encountered in equal
  mask = level_codes == -1

                                 ages  customer_id
city            customer_rating
Boston          2.0                 1            1
                3.0                 1            1
                7.0                 1            1
                8.0                 1            1
                9.0                 1            1
                N/A                12           12
Chicago         1.0                 1            1
                2.0                 2            2
                3.0                 1            1
                6.0                 1            1
                9.0                 1            1
                10.0                1            1
                N/A                12           12
New York        2.0                 3            3
                3.0                 3            3
                4.0                 2            2
                6.0                 1            1
                7.0                 2            2
                8.0                 3            3
                9.0                 1            1
                10.0                2            2
                N/A                13           13
San Francisco   1.0                 1            1
                4.0                 1            1
                5.0                 2            2
                7.0                 2            2
                8.0                 1            1
                9.0                 1            1
                N/A                15           15
Washington D.C. 5.0                 1            1
                6.0                 1            1
                8.0                 1            1
                10.0                1            1
                N/A                14           14

In [24]:
# average age of people that answered the survey
survey_answered = demo_ratings_outer[demo_ratings_outer['customer_rating'] != 'N/A']

round(survey_answered['ages'].mean())


# demo_outer_surveys['customer_rating'] != 'N/A'

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:284: RuntimeWarning: divide by zero encountered in less
  mask = indices < 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in greater_equal
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in less
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in bitwise_or
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\array_algos\take.py:534: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():

41

In [25]:
# find the average age of people that did not answer the survey
survey_non_answer = demo_ratings_outer[demo_ratings_outer['customer_rating'] == 'N/A']['ages'].mean()

round(survey_non_answer)

41

### Rolling Statistics and Time Series with Pandas

##### read_csv()

In [26]:
weather = pd.read_csv('files/chiweather.csv', sep = ';')

In [27]:
weather.head(10)

C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:254: RuntimeWarning: divide by zero encountered in isnan
  result = np.isnan(values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1498: RuntimeWarning: divide by zero encountered in absolute
  abs_vals = np.abs(self.values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1502: RuntimeWarning: divide by zero encountered in greater
  has_large_values = (abs_vals > 1e6).any()
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in less
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in greater
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in bitwise_and
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:254: RuntimeWarning: divide by zero encountered in isnan
  result = np.isnan(values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1498: RuntimeWarning: divide by zero encountered in absolute
  abs_vals = np.abs(self.values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1502: RuntimeWarning: divide by zero encountered in greater
  has_large_values = (abs_vals > 1e6).any()
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in less
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in greater
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in bitwise_and
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)

,Year,Month,Day,Hour,Minute,Temperature [2 m above gnd],Total Precipitation [sfc],Wind speed [10 m above gnd],Wind direction [10 m above gnd]
0,2017,11,25,0,0,51.85,0.0,17.31,327.13
1,2017,11,25,1,0,49.14,0.0,20.53,330.64
2,2017,11,25,2,0,46.42,0.0,21.41,327.80
3,2017,11,25,3,0,44.13,0.0,21.79,324.19
4,2017,11,25,4,0,42.22,0.0,21.03,321.91
5,2017,11,25,5,0,40.75,0.0,19.62,316.85
6,2017,11,25,6,0,40.71,0.0,19.17,318.31
7,2017,11,25,7,0,39.22,0.0,18.51,313.53
8,2017,11,25,8,0,39.49,0.0,18.73,310.16
9,2017,11,25,9,0,40.73,0.0,19.80,311.79

In [28]:
weather_update = weather.groupby(['Year','Month','Day']).mean().reset_index()

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexes\base.py:6015: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:795: RuntimeWarning: divide by zero encountered in int_scalars
  max_len = max(len(mgr_locs), taker.max() + 1)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:43: RuntimeWarning: divide by zero encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\array_algos\take.py:534: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1

In [29]:
weather_update.head(10)

C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:254: RuntimeWarning: divide by zero encountered in isnan
  result = np.isnan(values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1498: RuntimeWarning: divide by zero encountered in absolute
  abs_vals = np.abs(self.values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1502: RuntimeWarning: divide by zero encountered in greater
  has_large_values = (abs_vals > 1e6).any()
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in less
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in greater
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in bitwise_and
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:254: RuntimeWarning: divide by zero encountered in isnan
  result = np.isnan(values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1498: RuntimeWarning: divide by zero encountered in absolute
  abs_vals = np.abs(self.values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1502: RuntimeWarning: divide by zero encountered in greater
  has_large_values = (abs_vals > 1e6).any()
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in less
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in greater
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in bitwise_and
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)

,Year,Month,Day,Hour,Minute,Temperature [2 m above gnd],Total Precipitation [sfc],Wind speed [10 m above gnd],Wind direction [10 m above gnd]
0,2017,11,25,11.5,0.0,41.208750,0.000000,17.939583,325.761667
1,2017,11,26,11.5,0.0,38.298333,0.000000,11.435417,258.533750
2,2017,11,27,11.5,0.0,45.611250,0.000000,11.082500,188.377083
3,2017,11,28,11.5,0.0,48.497500,0.000000,17.418750,244.673333
4,2017,11,29,11.5,0.0,40.122917,0.020833,13.107083,167.510000
5,2017,11,30,11.5,0.0,43.618750,0.033333,14.343333,276.060000
6,2017,12,1,11.5,0.0,41.860417,0.000000,6.845000,223.459583
7,2017,12,2,11.5,0.0,45.324167,0.000000,8.934167,218.252500

##### shift() <br>
<p>Shift index by desired number of periods with an optional time freq</p>

In [30]:
# Print all keys for easier use
print(weather_update.keys())

weather_update['last_temp'] = weather_update['Temperature  [2 m above gnd]'].shift(1)

Index(['Year', 'Month', 'Day', 'Hour', 'Minute',
       'Temperature  [2 m above gnd]', 'Total Precipitation  [sfc]',
       'Wind speed  [10 m above gnd]', 'Wind direction  [10 m above gnd]'],
      dtype='object')

C:\Users\todds\anaconda3\lib\site-packages\numpy\core\numeric.py:1229: RuntimeWarning: divide by zero encountered in int_scalars
  shifts[ax] += sh
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\numeric.py:1233: RuntimeWarning: divide by zero encountered in int_scalars
  offset %= a.shape[ax] or 1  # If `a` is empty, nothing matters.

In [31]:
weather_update["Yesterday's Temp"] = weather_update['Temperature  [2 m above gnd]'].shift(1)

In [32]:
weather_update['difference'] = abs(weather_update['last_temp'] - weather_update['Temperature  [2 m above gnd]'])

weather_update

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\arraylike.py:364: RuntimeWarning: divide by zero encountered in absolute
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:254: RuntimeWarning: divide by zero encountered in isnan
  result = np.isnan(values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1498: RuntimeWarning: divide by zero encountered in absolute
  abs_vals = np.abs(self.values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1502: RuntimeWarning: divide by zero encountered in greater
  has_large_values = (abs_vals > 1e6).any()
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in less
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in greater
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in bitwise_and
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:254: RuntimeWarning: divide by zero encountered in isnan
  result = np.isnan(values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1498: RuntimeWarning: divide by zero encountered in absolute
  abs_vals = np.abs(self.values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1502: RuntimeWarning: divide by zero encountered in greater
  has_large_values = (abs_vals > 1e6).any()
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in less
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in greater
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in bitwise_and
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)

,Year,Month,Day,Hour,Minute,Temperature [2 m above gnd],Total Precipitation [sfc],Wind speed [10 m above gnd],Wind direction [10 m above gnd],last_temp,Yesterday's Temp,difference
0,2017,11,25,11.5,0.0,41.208750,0.000000,17.939583,325.761667,NaN,NaN,NaN
1,2017,11,26,11.5,0.0,38.298333,0.000000,11.435417,258.533750,41.208750,41.208750,2.910417
2,2017,11,27,11.5,0.0,45.611250,0.000000,11.082500,188.377083,38.298333,38.298333,7.312917
3,2017,11,28,11.5,0.0,48.497500,0.000000,17.418750,244.673333,45.611250,45.611250,2.886250
4,2017,11,29,11.5,0.0,40.122917,0.020833,13.107083,167.510000,48.497500,48.497500,8.374583
5,2017,11,30,11.5,0.0,43.618750,0.033333,14.343333,276.060000,40.122917,40.122917,3.495833
6,2017,12,1,11.5,0.0,41.860417,0.000000,6.845000,223.459583,43.618750,43.618750,1.758333
7,2017,12,2,11.5,0.0,45.324167,0.000000,8.934167,218.252500,41.860417,41.860417,3.463750

In [33]:
# create a new column that takes the difference in temperature from the previous day as an absolute value

In [34]:
weather_update['3-Day Avg'] = weather_update['Temperature   [2 m above gnd]'].rolling(window=3)
weather_update

KeyError: 'Temperature   [2 m above gnd]'

In [ ]:
# Pip install for both psycopg2 and SQLAlchemy
import sys
!{sys.executable} -m pip install psycopg2 SQLAlchemy

In [35]:
# databaselanguage(postgresql)://user:password@url:port/database_name
connection = 'postgresql://lgbiodph:cLAHE8kVQ0-SNI9ZlN5n-PIu09WtG_mF@queenie.db.elephantsql.com/lgbiodph'

weather_update['last_temp'] = weather_update['last_temp'].fillna(float(0))

In [ ]:
weather_update['difference'] = weather_update['difference'].fillna(float(0))

weather_update

In [36]:
# Writing a DataFrame to PostGreSQL database 
# from sqlalchemy.types import Integer, Text,String,DateTime,Float
from sqlalchemy.types import Integer, Text, String, DateTime, Float

weather_update.to_sql('chicago-weather', index=False, con = connection, if_exists = 'append',
                     schema = 'public', chunksize = 500, dtype = {
                         'year': String,
                         'month': String,
                         'day': String,
                         'minute': String,
                         'Temperature  [2 m above gnd]': Float,
                         'Total Precipitation  [sfc]': Float ,
                         'Wind speed  [10 m above gnd]': Float ,
                         'Wind direction  [10 m above gnd]': Float ,
                         'last_temp': Float,
                         'difference': Float
                     })

In [ ]:
chi_weather_sql = pd.read_sql_table('chicago-weather', con = connection)

chi_weather_sql